# Generated by Django 2.2.4 on 2019-09-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_auto_20190908_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureDetails',
            fields=[
                ('insured_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('insured_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insured_dob', models.DateField(blank=True, null=True)),
                ('insured_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('insured_profission', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_addr_code', models.IntegerField(blank=True, null=True)),
                ('insured_phone_no', models.BigIntegerField(blank=True, null=True)),
                ('insured_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='policyAgentCommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.IntegerField(blank=True)),
                ('agent_id', models.CharField(blank=True, max_length=120, null=True)),
                ('prod_code', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyBills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_no', models.IntegerField(blank=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('policy_no', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_issued_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=20, null=True)),
                ('renewal_no', models.BigIntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_code', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.AgentMaster')),
                ('insured_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='underwriter.InsureDetails')),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.ProductMaster')),
            ],
        ),
        migrations.CreateModel(
            name='policyVehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.IntegerField(blank=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_model_id', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_number', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='policyRiskDetails',
            fields=[
                ('policy_risk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('risk_description', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_SA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_no', models.ForeignKey(blank=True, db_column='policy_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='underwriter.PolicyDetails')),
                ('risk_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.ProductRiskMaster')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredAddress',
            fields=[
                ('insured_addr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_city', models.CharField(blank=True, max_length=20, null=True)),
                ('insured_state', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_country', models.CharField(blank=True, max_length=20, null=True)),
                ('insured_pincode', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_id', models.ForeignKey(blank=True, db_column='insured_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='underwriter.InsureDetails')),
            ],
        ),
    ]
