# Generated by Django 2.2.4 on 2019-09-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMaster',
            fields=[
                ('agent_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_dob', models.DateField(blank=True, null=True)),
                ('agent_age', models.IntegerField(blank=True, null=True)),
                ('agent_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_join_date', models.DateField(auto_now_add=True, null=True)),
                ('agent_start_date', models.DateField(blank=True, null=True)),
                ('agent_end_date', models.DateField(blank=True, null=True)),
                ('agent_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('prod_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prod_description', models.CharField(blank=True, max_length=250, null=True)),
                ('prod_start_date', models.DateField(blank=True, null=True)),
                ('prod_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRiskMaster',
            fields=[
                ('risk_code', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('risk_description', models.CharField(blank=True, max_length=500, null=True)),
                ('risk_premium_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_start_date', models.DateField(blank=True, null=True)),
                ('risk_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('prem_calc_method', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_si', models.BigIntegerField(blank=True, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.ProductMaster')),
            ],
        ),
    ]
