# Generated by Django 2.2.4 on 2019-09-07 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsSurveyorMaster',
            fields=[
                ('surveyor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surveyor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_qualificaition', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_brach_code', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_status_code', models.CharField(max_length=200, unique=True)),
                ('clm_status_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDepriciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_age_from', models.IntegerField(blank=True, null=True)),
                ('vehicle_age_to', models.IntegerField(blank=True, null=True)),
                ('dep_percent_on_idv', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_id', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_cubic_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('insured_declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agentmaster',
            name='agent_join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NCBMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_years_from', models.BigIntegerField(blank=True, null=True)),
                ('no_of_years_to', models.BigIntegerField(blank=True, null=True)),
                ('discount_on_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.ProductMaster')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_prod_comm_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.AgentMaster')),
                ('prod_code', models.ForeignKey(db_column='prod_code', on_delete=django.db.models.deletion.DO_NOTHING, to='master.ProductMaster')),
            ],
        ),
    ]
